"""product.video_download_url

Revision ID: 3d483c13007d
Revises: c0937743f21c
Create Date: 2026-07-28 10:30:04.794155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d483c13007d'
down_revision: Union[str, Sequence[str], None] = 'c0937743f21c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('video_download_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'video_download_url')
    # ### end Alembic commands ###
