"""sellers and products tables

Revision ID: 4c1e92d224d7
Revises: 28c966a5ccf9
Create Date: 2026-07-23 17:33:40.942511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c1e92d224d7'
down_revision: Union[str, Sequence[str], None] = '28c966a5ccf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('tiktok_username', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tiktok_username')
    )
    op.create_index(op.f('ix_sellers_handle'), 'sellers', ['handle'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('tiktok_video_id', sa.String(length=30), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('hashtags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_kes', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', name='productstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status != 'published' OR price_kes IS NOT NULL", name='ck_products_published_needs_price'),
    sa.CheckConstraint('stock >= 0', name='ck_products_stock_non_negative'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tiktok_video_id')
    )
    op.create_index(op.f('ix_products_seller_id'), 'products', ['seller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_seller_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_sellers_handle'), table_name='sellers')
    op.drop_table('sellers')
    # ### end Alembic commands ###
