"""link seller to account, add follower_count

Revision ID: df9c84f7bf50
Revises: bcfb8e233284
Create Date: 2026-07-25 21:57:30.291085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9c84f7bf50'
down_revision: Union[str, Sequence[str], None] = 'bcfb8e233284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('sellers', sa.Column('follower_count', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_sellers_account_id'), 'sellers', ['account_id'], unique=True)
    op.create_foreign_key(None, 'sellers', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sellers', type_='foreignkey')
    op.drop_index(op.f('ix_sellers_account_id'), table_name='sellers')
    op.drop_column('sellers', 'follower_count')
    op.drop_column('sellers', 'account_id')
    # ### end Alembic commands ###
